"""
patch_notebook_v4.py — python -X utf8 patch_notebook_v4.py
Insert co-occurrence + t-SNE cells BEFORE Cell 21 (Zip).
Also fix cells 11,13 back to raw if they were accidentally turned to code.
"""
import json, copy
from pathlib import Path

NB = Path("notebooks/cv-eval-test.ipynb")
nb = json.loads(NB.read_text(encoding="utf-8"))


def src_lines(lines):
    out = []
    for i, l in enumerate(lines):
        out.append(l + ("\n" if i < len(lines) - 1 else ""))
    return out


def code_cell(cid, lines):
    return {"cell_type":"code","execution_count":None,"id":cid,
            "metadata":{"tags":[]},"outputs":[],"source":src_lines(lines)}


def md_cell(cid, text):
    return {"cell_type":"markdown","id":cid,
            "metadata":{"tags":[]},"source":[text]}


# ══════════════════════════════════════════════════════════════
COOC_SOURCE = [
"# ── Co-occurrence Heatmap ────────────────────────────────────",
"# Multi-label: không có confusion matrix chuẩn.",
"# Thay bằng Phi-coefficient co-occurrence giữa các cặp class.",
"import numpy as np, json, sys, torch",
"import matplotlib.pyplot as plt",
"from pathlib import Path",
"",
"sys.path.insert(0, str(REPO_DIR / 'src'))",
"from dataset import COCOMultiLabelDataset, get_val_transform",
"from models import build_model",
"",
"COCO_ROOT  = '/kaggle/input/datasets/awsaf49/coco-2017-dataset/coco2017'",
"SUBSET_DIR = Path('/kaggle/working/data/coco_subset')",
"OUTPUTS_DIR= Path('/kaggle/working/outputs')",
"DEVICE     = 'cuda' if torch.cuda.is_available() else 'cpu'",
"",
"COCO_CATS = [",
"    'person','bicycle','car','motorcycle','airplane','bus','train','truck','boat',",
"    'traffic light','fire hydrant','stop sign','parking meter','bench','bird',",
"    'cat','dog','horse','sheep','cow','elephant','bear','zebra','giraffe',",
"    'backpack','umbrella','handbag','tie','suitcase','frisbee','skis','snowboard',",
"    'sports ball','kite','baseball bat','baseball glove','skateboard','surfboard',",
"    'tennis racket','bottle','wine glass','cup','fork','knife','spoon','bowl',",
"    'banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza',",
"    'donut','cake','chair','couch','potted plant','bed','dining table','toilet',",
"    'tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven',",
"    'toaster','sink','refrigerator','book','clock','vase','scissors','teddy bear',",
"    'hair drier','toothbrush'",
"]",
"",
"# Load train labels",
"transform = get_val_transform(img_size=224)",
"train_ids = json.load(open(SUBSET_DIR / 'subset_train_ids.json'))",
"train_ds  = COCOMultiLabelDataset(COCO_ROOT, 'train', transform, train_ids)",
"labels = np.array([lbl.numpy() for _, lbl in train_ds])  # (N,80)",
"N = len(labels)",
"print(f'Train labels loaded: {labels.shape}')",
"",
"# Phi co-occurrence",
"freq  = labels.sum(0) / N",
"cooc  = (labels.T @ labels) / N",
"denom = np.sqrt(np.outer(freq, freq))",
"denom[denom == 0] = 1",
"phi   = cooc / denom",
"np.fill_diagonal(phi, 0)",
"",
"# Top-30 frequent classes",
"top30  = np.argsort(freq)[::-1][:30]",
"phi30  = phi[np.ix_(top30, top30)]",
"cats30 = [COCO_CATS[i] for i in top30]",
"",
"fig, ax = plt.subplots(figsize=(14, 12))",
"im = ax.imshow(phi30, cmap='YlOrRd', aspect='auto')",
"ax.set_xticks(range(30)); ax.set_xticklabels(cats30, rotation=90, fontsize=7)",
"ax.set_yticks(range(30)); ax.set_yticklabels(cats30, fontsize=7)",
"plt.colorbar(im, ax=ax, fraction=0.03, label='Phi coefficient')",
"ax.set_title('Co-occurrence Heatmap — Top-30 Frequent Classes (Train set)',",
"             fontsize=12, fontweight='bold')",
"for i in range(30):",
"    for j in range(30):",
"        if phi30[i,j] > 0.35:",
"            ax.text(j, i, f'{phi30[i,j]:.2f}', ha='center', va='center', fontsize=6)",
"plt.tight_layout()",
"plt.savefig(str(OUTPUTS_DIR / 'cooccurrence_heatmap.png'), dpi=120)",
"plt.show()",
"",
"pairs = sorted([(phi[i,j], COCO_CATS[i], COCO_CATS[j])",
"                for i in range(80) for j in range(i+1,80)], reverse=True)",
"print('Top-10 co-occurring pairs:')",
"for v,a,b in pairs[:10]: print(f'  {a:20s} <-> {b:20s}  phi={v:.3f}')",
"",
"# FP analysis with Exp C",
"pth = OUTPUTS_DIR / 'exp_C_efficientnet_cbam_asl' / 'best.pth'",
"if pth.exists():",
"    test_ids = json.load(open(SUBSET_DIR / 'subset_test_ids.json'))",
"    test_ds  = COCOMultiLabelDataset(COCO_ROOT, 'val', transform, test_ids)",
"    loader   = torch.utils.data.DataLoader(test_ds, batch_size=64, num_workers=2)",
"    model    = build_model({'backbone':'efficientnet_b0','use_cbam':True,",
"                            'num_classes':80,'pretrained':False}).to(DEVICE)",
"    ckpt = torch.load(pth, map_location=DEVICE, weights_only=False)",
"    model.load_state_dict(ckpt['model'] if 'model' in ckpt else ckpt)",
"    model.eval()",
"    all_p, all_t = [], []",
"    with torch.no_grad():",
"        for imgs, tgts in loader:",
"            all_p.append(torch.sigmoid(model(imgs.to(DEVICE))).cpu().numpy())",
"            all_t.append(tgts.numpy())",
"    P = np.concatenate(all_p); T = np.concatenate(all_t)",
"    pred = (P >= 0.5).astype(int)",
"    FP_mat = np.zeros((80, 80), dtype=int)",
"    for n in range(len(T)):",
"        fp  = np.where((pred[n]==1) & (T[n]==0))[0]",
"        gt  = np.where(T[n]==1)[0]",
"        for f in fp:",
"            for g in gt: FP_mat[f, g] += 1",
"    fp_pairs = sorted([(FP_mat[i,j], COCO_CATS[i], COCO_CATS[j])",
"                       for i in range(80) for j in range(80) if i!=j and FP_mat[i,j]>0],",
"                      reverse=True)",
"    print('\\nTop-10 FP confusion pairs:')",
"    for cnt,a,b in fp_pairs[:10]:",
"        print(f'  Predict [{a:20s}] when GT=[{b:20s}]  count={cnt}')",
"else:",
"    print('Exp C best.pth not found')",
]

TSNE_SOURCE = [
"# ── t-SNE Feature Space Visualization ────────────────────────",
"# Extract GAP vectors (1280-dim) -> PCA(50) -> t-SNE(2D)",
"import torch, json, sys",
"import numpy as np",
"import matplotlib.pyplot as plt",
"from pathlib import Path",
"from sklearn.manifold import TSNE",
"from sklearn.decomposition import PCA",
"from sklearn.metrics.pairwise import cosine_distances",
"",
"sys.path.insert(0, str(REPO_DIR / 'src'))",
"from models import build_model",
"from dataset import COCOMultiLabelDataset, get_val_transform",
"",
"COCO_ROOT  = '/kaggle/input/datasets/awsaf49/coco-2017-dataset/coco2017'",
"SUBSET_DIR = Path('/kaggle/working/data/coco_subset')",
"OUTPUTS_DIR= Path('/kaggle/working/outputs')",
"DEVICE     = 'cuda' if torch.cuda.is_available() else 'cpu'",
"",
"COCO_CATS = [",
"    'person','bicycle','car','motorcycle','airplane','bus','train','truck','boat',",
"    'traffic light','fire hydrant','stop sign','parking meter','bench','bird',",
"    'cat','dog','horse','sheep','cow','elephant','bear','zebra','giraffe',",
"    'backpack','umbrella','handbag','tie','suitcase','frisbee','skis','snowboard',",
"    'sports ball','kite','baseball bat','baseball glove','skateboard','surfboard',",
"    'tennis racket','bottle','wine glass','cup','fork','knife','spoon','bowl',",
"    'banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza',",
"    'donut','cake','chair','couch','potted plant','bed','dining table','toilet',",
"    'tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven',",
"    'toaster','sink','refrigerator','book','clock','vase','scissors','teddy bear',",
"    'hair drier','toothbrush'",
"]",
"",
"pth = OUTPUTS_DIR / 'exp_C_efficientnet_cbam_asl' / 'best.pth'",
"if not pth.exists():",
"    print('Exp C best.pth not found'); raise SystemExit",
"",
"model = build_model({'backbone':'efficientnet_b0','use_cbam':True,",
"                     'num_classes':80,'pretrained':False}).to(DEVICE)",
"ckpt  = torch.load(pth, map_location=DEVICE, weights_only=False)",
"model.load_state_dict(ckpt['model'] if 'model' in ckpt else ckpt)",
"model.eval()",
"",
"# Hook on GAP (adaptive_avg_pool before FC)",
"captured = {}",
"def hook_fn(m, inp, out):",
"    v = out.detach().cpu()",
"    captured['feat'] = v.flatten(1)  # (B, 1280)",
"hook = model.gap.register_forward_hook(hook_fn)",
"",
"transform  = get_val_transform(img_size=224)",
"val_ids    = json.load(open(SUBSET_DIR / 'subset_val_ids.json'))",
"val_ds     = COCOMultiLabelDataset(COCO_ROOT, 'val', transform, val_ids)",
"val_loader = torch.utils.data.DataLoader(val_ds, batch_size=64, num_workers=2)",
"",
"feats, lbls = [], []",
"with torch.no_grad():",
"    for imgs, tgts in val_loader:",
"        _ = model(imgs.to(DEVICE))",
"        feats.append(captured['feat'].numpy())",
"        lbls.append(tgts.numpy())",
"hook.remove()",
"",
"F = np.concatenate(feats, 0)   # (N,1280)",
"L = np.concatenate(lbls,  0)   # (N,80)",
"print(f'Features: {F.shape}, Labels: {L.shape}')",
"",
"# PCA -> t-SNE",
"print('PCA 1280->50...')",
"pca = PCA(n_components=50, random_state=42)",
"F50 = pca.fit_transform(F)",
"print(f'PCA variance: {pca.explained_variance_ratio_.sum():.1%}')",
"print('t-SNE 50->2 (may take ~2min)...')",
"tsne = TSNE(n_components=2, perplexity=40, n_iter=1000, random_state=42, verbose=0)",
"F2   = tsne.fit_transform(F50)",
"",
"# Plot coloured by top-8 frequent classes",
"freq_order   = np.argsort(L.sum(0))[::-1][:8]",
"label_colors = plt.cm.Set1(np.linspace(0, 0.85, 8))",
"",
"fig, ax = plt.subplots(figsize=(13, 10))",
"ax.scatter(F2[:,0], F2[:,1], c='lightgray', s=8, alpha=0.25, label='other')",
"for k, ci in enumerate(freq_order):",
"    mask = L[:, ci] == 1",
"    ax.scatter(F2[mask,0], F2[mask,1], c=[label_colors[k]], s=14,",
"               alpha=0.75, label=COCO_CATS[ci])",
"ax.set_title('t-SNE of GAP Features — Exp C (Val 1k samples)',",
"             fontsize=12, fontweight='bold')",
"ax.legend(markerscale=2, fontsize=9)",
"ax.axis('off')",
"plt.tight_layout()",
"plt.savefig(str(OUTPUTS_DIR / 'tsne_features_expC.png'), dpi=120)",
"plt.show()",
"print('Saved: tsne_features_expC.png')",
"",
"# Intra vs Inter cosine distance per class",
"print('\\nIntra vs Inter cosine distance (top-5 classes):')",
"print(f'  {\"Class\":20s}  {\"Intra\":>8}  {\"Inter\":>8}  Overlap?')",
"for ci in freq_order[:5]:",
"    cf  = F[L[:,ci]==1]",
"    oth = F[L[:,ci]==0][:300]",
"    if len(cf) < 2: continue",
"    intra = cosine_distances(cf).mean()",
"    inter = cosine_distances(cf, oth).mean()",
"    ov    = 'YES (confused)' if intra > 0.5 * inter else 'NO (clear cluster)'",
"    print(f'  {COCO_CATS[ci]:20s}  {intra:8.4f}  {inter:8.4f}  {ov}')",
]

# Insert before Cell 21 (Zip)
new_cells = []
for cell in nb["cells"]:
    src = "".join(cell.get("source", []))
    if cell.get("cell_type") == "markdown" and "Cell 21: Zip" in src:
        new_cells.append(md_cell("cooc_md",
            "## Co-occurrence Heatmap (Multi-label Confusion Matrix)\n"))
        new_cells.append(code_cell("cooc_code", COOC_SOURCE))
        new_cells.append(md_cell("tsne_md",
            "## t-SNE: Feature Space Visualization (GAP vectors, Exp C)\n"))
        new_cells.append(code_cell("tsne_code", TSNE_SOURCE))
        print("[v4] Inserted co-occurrence + t-SNE cells before Zip")
    new_cells.append(cell)

nb["cells"] = new_cells
NB.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Done. Total cells: {len(new_cells)}")
